/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTalaChatRouteImport } from './routes/api/tala-chat'
import { Route as AuthenticatedWorksheetRouteImport } from './routes/_authenticated/worksheet'
import { Route as AuthenticatedTranslatorRouteImport } from './routes/_authenticated/translator'
import { Route as AuthenticatedTosRouteImport } from './routes/_authenticated/tos'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRubricRouteImport } from './routes/_authenticated/rubric'
import { Route as AuthenticatedRewriterRouteImport } from './routes/_authenticated/rewriter'
import { Route as AuthenticatedPptRouteImport } from './routes/_authenticated/ppt'
import { Route as AuthenticatedLessonPlansRouteImport } from './routes/_authenticated/lesson-plans'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminModulesRouteImport } from './routes/_authenticated/admin/modules'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin/approvals'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTalaChatRoute = ApiTalaChatRouteImport.update({
  id: '/api/tala-chat',
  path: '/api/tala-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorksheetRoute = AuthenticatedWorksheetRouteImport.update({
  id: '/worksheet',
  path: '/worksheet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTranslatorRoute = AuthenticatedTranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTosRoute = AuthenticatedTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRubricRoute = AuthenticatedRubricRouteImport.update({
  id: '/rubric',
  path: '/rubric',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewriterRoute = AuthenticatedRewriterRouteImport.update({
  id: '/rewriter',
  path: '/rewriter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPptRoute = AuthenticatedPptRouteImport.update({
  id: '/ppt',
  path: '/ppt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonPlansRoute =
  AuthenticatedLessonPlansRouteImport.update({
    id: '/lesson-plans',
    path: '/lesson-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminModulesRoute =
  AuthenticatedAdminModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/lesson-plans': typeof AuthenticatedLessonPlansRoute
  '/ppt': typeof AuthenticatedPptRoute
  '/rewriter': typeof AuthenticatedRewriterRoute
  '/rubric': typeof AuthenticatedRubricRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tos': typeof AuthenticatedTosRoute
  '/translator': typeof AuthenticatedTranslatorRoute
  '/worksheet': typeof AuthenticatedWorksheetRoute
  '/api/tala-chat': typeof ApiTalaChatRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/lesson-plans': typeof AuthenticatedLessonPlansRoute
  '/ppt': typeof AuthenticatedPptRoute
  '/rewriter': typeof AuthenticatedRewriterRoute
  '/rubric': typeof AuthenticatedRubricRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tos': typeof AuthenticatedTosRoute
  '/translator': typeof AuthenticatedTranslatorRoute
  '/worksheet': typeof AuthenticatedWorksheetRoute
  '/api/tala-chat': typeof ApiTalaChatRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/lesson-plans': typeof AuthenticatedLessonPlansRoute
  '/_authenticated/ppt': typeof AuthenticatedPptRoute
  '/_authenticated/rewriter': typeof AuthenticatedRewriterRoute
  '/_authenticated/rubric': typeof AuthenticatedRubricRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tos': typeof AuthenticatedTosRoute
  '/_authenticated/translator': typeof AuthenticatedTranslatorRoute
  '/_authenticated/worksheet': typeof AuthenticatedWorksheetRoute
  '/api/tala-chat': typeof ApiTalaChatRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/admin'
    | '/assessments'
    | '/dashboard'
    | '/documents'
    | '/lesson-plans'
    | '/ppt'
    | '/rewriter'
    | '/rubric'
    | '/settings'
    | '/tos'
    | '/translator'
    | '/worksheet'
    | '/api/tala-chat'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/content'
    | '/admin/logs'
    | '/admin/modules'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/assessments'
    | '/dashboard'
    | '/documents'
    | '/lesson-plans'
    | '/ppt'
    | '/rewriter'
    | '/rubric'
    | '/settings'
    | '/tos'
    | '/translator'
    | '/worksheet'
    | '/api/tala-chat'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/content'
    | '/admin/logs'
    | '/admin/modules'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/assessments'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/lesson-plans'
    | '/_authenticated/ppt'
    | '/_authenticated/rewriter'
    | '/_authenticated/rubric'
    | '/_authenticated/settings'
    | '/_authenticated/tos'
    | '/_authenticated/translator'
    | '/_authenticated/worksheet'
    | '/api/tala-chat'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/modules'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiTalaChatRoute: typeof ApiTalaChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tala-chat': {
      id: '/api/tala-chat'
      path: '/api/tala-chat'
      fullPath: '/api/tala-chat'
      preLoaderRoute: typeof ApiTalaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/worksheet': {
      id: '/_authenticated/worksheet'
      path: '/worksheet'
      fullPath: '/worksheet'
      preLoaderRoute: typeof AuthenticatedWorksheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/translator': {
      id: '/_authenticated/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof AuthenticatedTranslatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tos': {
      id: '/_authenticated/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof AuthenticatedTosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rubric': {
      id: '/_authenticated/rubric'
      path: '/rubric'
      fullPath: '/rubric'
      preLoaderRoute: typeof AuthenticatedRubricRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewriter': {
      id: '/_authenticated/rewriter'
      path: '/rewriter'
      fullPath: '/rewriter'
      preLoaderRoute: typeof AuthenticatedRewriterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ppt': {
      id: '/_authenticated/ppt'
      path: '/ppt'
      fullPath: '/ppt'
      preLoaderRoute: typeof AuthenticatedPptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson-plans': {
      id: '/_authenticated/lesson-plans'
      path: '/lesson-plans'
      fullPath: '/lesson-plans'
      preLoaderRoute: typeof AuthenticatedLessonPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modules': {
      id: '/_authenticated/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AuthenticatedAdminModulesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminModulesRoute: typeof AuthenticatedAdminModulesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
    AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminModulesRoute: AuthenticatedAdminModulesRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedLessonPlansRoute: typeof AuthenticatedLessonPlansRoute
  AuthenticatedPptRoute: typeof AuthenticatedPptRoute
  AuthenticatedRewriterRoute: typeof AuthenticatedRewriterRoute
  AuthenticatedRubricRoute: typeof AuthenticatedRubricRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTosRoute: typeof AuthenticatedTosRoute
  AuthenticatedTranslatorRoute: typeof AuthenticatedTranslatorRoute
  AuthenticatedWorksheetRoute: typeof AuthenticatedWorksheetRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedLessonPlansRoute: AuthenticatedLessonPlansRoute,
  AuthenticatedPptRoute: AuthenticatedPptRoute,
  AuthenticatedRewriterRoute: AuthenticatedRewriterRoute,
  AuthenticatedRubricRoute: AuthenticatedRubricRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTosRoute: AuthenticatedTosRoute,
  AuthenticatedTranslatorRoute: AuthenticatedTranslatorRoute,
  AuthenticatedWorksheetRoute: AuthenticatedWorksheetRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiTalaChatRoute: ApiTalaChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
